apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: scenario-1-quorum-violation
  namespace: university-chaos
  labels:
    app.kubernetes.io/part-of: university-chaos
    scenario: "1"
    invariant: "quorum"
spec:
  action: pod-kill
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - university-app
    labelSelectors:
      app.kubernetes.io/name: enrollment-service
      app.kubernetes.io/part-of: university-app
